define({
  root: ({
    _widgetLabel: "Marketing Planning",
    subTitle:"Sales Forecasting Application",
    texto:"text",
    addLocation:"Add location",
    removeAllLocation:"Remove all locations",
    infoInsertPoint:"Click on map or enter address(es) for location",
    calculate:"Calculate",
    CalculateGP:"Calculate...",
    Cancel:"Cancel",
    saveResult:"Save Results",
    back:"Back",
    titleMessageValidation:"Validation",
    messageValidation:"Some values are missing.",
    titleErrorCall:"Error",
    storeName:"Store name",
    placeHolderStoreName:"Store Name",
    helpStoreName:"Store name",
    storeID:"Store ID",
    placeHolderStoreID:"Store ID",
    helpStoreID:"Store ID",
    FormatTitle:"Format",
    helpFormat:"Help Format",
    titleEnvironment:"Environment",
    helpEnvironment:"Help Environment",
    titleRentableSQFT:"Rentable Sq Ft",
    placeHoldertRentableSQFT:"Insert numeric value",
    helpRentableSQFT:"Rentable Sq Ft",
    titleSellingSquareFootage:"Selling Square Footage",
    placeHolderSellingSquareFootage:"Selling Square Footage",
    helpSellingSquareFootage:"Selling Square Footage",
    titleOwner:"Owner",
    helpOwner:"Help Owner",
    titleCityTier:"City Tier",
    Age_Store_sq2:"AgeStore",
    helpCityTier:"City Tier",
    textColocateWithJewelryStore:"Colocate with jewelry store(y/n)",
    helpColocateWithJewelryStore:"Colocate with jewelry store",
    titleCotenants:"Cotenants",
    helpCotenants:"Cotenants select",
    titleNotes:"Notes",
    placeHolderNotes:"Notes",
    helpNotes:"Notes Values",
    msgSuccess:"Sales Estimate: $",
    titleCheckLayer:"Show prior results",
    Sales:"Cannibalization",
    Analogs:"Store Name",
    StoreIDs:"Store ID"

  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 1,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0,
  "zh-hk": 0,
  "zh-tw": 0
});
