define({
  root: ({
    _widgetLabel: "Marketing Planning",
    subTitle:"Sales Forecasting Application",
    texto:"text",
    addLocation:"Add location",
    removeAllLocation:"Remove all locations",
    infoInsertPoint:"Click on map or enter address(es) for location",
    calculate:"Calculate",
    CalculateGP:"Calculate...",
    Cancel:"Cancel",
    saveResult:"Save Results",
    back:"Back",
    titleMessageValidation:"Validation",
    messageValidation:"Some values are missing.",
    titleErrorCall:"Error",
    storeName:"Store name",
    placeHolderStoreName:"Store Name",
    helpStoreName:"Store name",
    storeID:"Store ID",
    placeHolderStoreID:"Store ID",
    helpStoreID:"Store ID",
    FormatTitle:"Format",
    helpFormat:"Help Format",
    titleEnvironment:"Environment",
    helpEnvironment:"Help Environment",
    titleRentableSQFT:"Rentable Sq Ft",
    placeHoldertRentableSQFT:"Insert numeric value",
    helpRentableSQFT:"Rentable Sq Ft",
    titleSellingSquareFootage:"Selling Square Footage",
    placeHolderSellingSquareFootage:"Selling Square Footage",
    helpSellingSquareFootage:"Selling Square Footage",
    titleOwner:"Owner",
    helpOwner:"Help Owner",
    titleCityTier:"City Tier",
    Age_Store_sq2:"AgeStore",
    helpCityTier:"City Tier",
    textColocateWithJewelryStore:"Colocate with jewelry store(y/n)",
    helpColocateWithJewelryStore:"Colocate with jewelry store",
    titleCotenants:"Cotenants",
    helpCotenants:"Cotenants select",
    titleNotes:"Notes",
    placeHolderNotes:"Notes",
    helpNotes:"Notes Values",
    msgSuccess:"Sales Estimate: $",
    titleCheckLayer:"Show prior results",
    Sales:"Cannibalization",
    Analogs:"Store Name",
    StoreIDs:"Store ID",
    valuesFieldError: "Error saving widget fields"
  })
});
